In [9]:
# !pip install geopandas
# !pip install cities_coordinates

In [10]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import geopandas as gpd

In [11]:
tournaments = pd.read_csv('tournaments_preparation.csv')
all_match = pd.read_csv('all_match_preparation.csv')
# country_points = pd.read_csv('country_points.csv')
#city_points =gpd.read_file('https://raw.githubusercontent.com/drei01/geojson-world-cities/master/cities.geojson')

#https://github.com/sofzer/cities_coordinates
from cities_coordinates import CityCoordinator
# c=CityCoordinator()

In [12]:
tournaments.head()

,Unnamed: 0,tourney_year_id,tourney_order,tourney_type,tourney_name,tourney_id,tourney_slug,tourney_location,tourney_date,year,...,doubles_winner_1_player_id,doubles_winner_2_name,doubles_winner_2_player_slug,doubles_winner_2_player_id,tourney_fin_commit_USD,tourney_region,tourney_city,country_code,latitude,longitude
0,0,2010-339,1,ATP 250,Brisbane,339,brisbane,Brisbane,2010-01-03,2010,...,ca12,Marc Gicquel,marc-gicquel,g436,424250.0,Oceania,Brisbane,AU,-27.46794,153.02809
1,1,2010-451,2,ATP 250,Doha,451,doha,Doha,2010-01-04,2010,...,g476,Albert Montanes,albert-montanes,m824,1110250.0,Asia,Doha,QA,25.28545,51.53096
2,2,2010-891,3,ATP 250,Chennai,891,chennai,Chennai,2010-01-04,2010,...,g710,Santiago Ventura,santiago-ventura,v251,450000.0,Asia,Chennai,IN,13.08784,80.27847
3,3,2010-338,4,ATP 250,Sydney,338,sydney,Sydney,2010-01-11,2010,...,n210,Nenad Zimonjic,nenad-zimonjic,z072,424250.0,Oceania,Sydney,AU,-33.86785,151.20732
4,4,2010-301,5,ATP 250,Auckland,301,auckland,Auckland,2010-01-11,2010,...,d763,Horia Tecau,horia-tecau,t749,407250.0,Oceania,Auckland,NZ,-36.84853,174.76349

In [13]:
tournaments['tourney_location'].unique()

array(['Brisbane', 'Doha', 'Chennai', 'Sydney', 'Auckland',
       'Johannesburg', 'Santiago', 'San Jose', 'Costa do Sauipe',
       'Memphis', 'Buenos Aires', 'Dubai, United Arab Emirates',
       'Acapulco, Mexico', 'Delray Beach', 'Indian Wells', 'Miami',
       'Houston, United States', 'Newport, United States',
       'Atlanta, United States', 'Los Angeles, United States',
       'Washington, United States', 'Toronto, Canada',
       'Cincinnati, United States', 'New Haven', 'New York',
       'Kuala Lumpur', 'Bangkok', 'Beijing, China', 'Tokyo',
       'Shanghai, China', 'Moscow, Russia', 'St. Petersburg, Russia',
       'London, Great Britain', 'Brisbane, Australia', 'Doha, Qatar',
       'Chennai, India', 'Sydney, Australia', 'Auckland, New Zealand',
       'Johannesburg, South Africa', 'Santiago, Chile',
       'San Jose, United States', 'Costa do Sauipe, Brazil',
       'Memphis, United States', 'Buenos Aires, Argentina',
       'Delray Beach, United States', 'Indian Wells, United States',
       'Miami, United States', 'Montreal, Canada',
       'Winston-Salem, United States', 'New York, United States',
       'Kuala Lumpur, Malaysia', 'Bangkok, Thailand', 'Tokyo, Japan',
       'Vina del Mar, Chile', 'Sao Paulo, Brazil', 'Bogota, Colombia',
       'Rio de Janeiro, Brazil', 'New York City, United States',
       'Shenzhen, China', 'Quito, Ecuador', 'Los Cabos, Mexico',
       'Chengdu, China', 'Milan, Italy', 'Pune, India',
       'Cordoba, Argentina', 'Zhuhai, China', 'Melbourne',
       'Melbourne, Australia', 'Zagreb', 'Rotterdam', 'Marseille, France',
       'Casablanca', 'Monte Carlo', 'Barcelona', 'Rome',
       'Munich, Germany', 'Estoril', 'Belgrade', 'Madrid, Spain',
       'Nice, France', 'Paris, France', 'Halle, Germany',
       'Eastbourne, Great Britain', 's-Hertogenbosch, Netherlands',
       'Bastad, Sweden', 'Stuttgart, Germany', 'Hamburg, Germany',
       'Gstaad, Switzerland', 'Umag, Croatia', 'Metz', 'Bucharest',
       'Stockholm', 'Montpellier, France', 'Vienna, Austria',
       'Valencia, Switzerland', 'Basel, Switzerland', 'Zagreb, Croatia',
       'Rotterdam, Netherlands', 'Casablanca, Morocco',
       'Monte Carlo, Monaco', 'Barcelona, Spain', 'Estoril, Portugal',
       'Belgrade, Serbia', 'Rome, Italy', 'Kitzbhel, Austria',
       'Metz, France', 'Bucharest, Romania', 'Stockholm, Sweden',
       'Valencia, Spain', 'Bâ€ stad, Sweden', 'Kitzbuhel, Austria',
       'Monte-Carlo, Monaco', 'Oeiras, Portugal', 'Dusseldorf, Germany',
       'Istanbul, Turkey', 'Geneva, Switzerland',
       'Nottingham, Great Britain', 'Sofia, Bulgaria',
       'Marrakech, Morocco', 'Antwerp, Belgium', 'Budapest, Hungary',
       'Lyon, France', 'Antalya, Turkey'], dtype=object)

In [14]:
#Create a new column called "tourney_city"

#Using split with the comma and keeping only the first part 
tournaments['tourney_city'] = tournaments['tourney_location'].str.split(',').str[0]

In [15]:
tournaments['tourney_city'].unique()

array(['Brisbane', 'Doha', 'Chennai', 'Sydney', 'Auckland',
       'Johannesburg', 'Santiago', 'San Jose', 'Costa do Sauipe',
       'Memphis', 'Buenos Aires', 'Dubai', 'Acapulco', 'Delray Beach',
       'Indian Wells', 'Miami', 'Houston', 'Newport', 'Atlanta',
       'Los Angeles', 'Washington', 'Toronto', 'Cincinnati', 'New Haven',
       'New York', 'Kuala Lumpur', 'Bangkok', 'Beijing', 'Tokyo',
       'Shanghai', 'Moscow', 'St. Petersburg', 'London', 'Montreal',
       'Winston-Salem', 'Vina del Mar', 'Sao Paulo', 'Bogota',
       'Rio de Janeiro', 'New York City', 'Shenzhen', 'Quito',
       'Los Cabos', 'Chengdu', 'Milan', 'Pune', 'Cordoba', 'Zhuhai',
       'Melbourne', 'Zagreb', 'Rotterdam', 'Marseille', 'Casablanca',
       'Monte Carlo', 'Barcelona', 'Rome', 'Munich', 'Estoril',
       'Belgrade', 'Madrid', 'Nice', 'Paris', 'Halle', 'Eastbourne',
       's-Hertogenbosch', 'Bastad', 'Stuttgart', 'Hamburg', 'Gstaad',
       'Umag', 'Metz', 'Bucharest', 'Stockholm', 'Montpellier', 'Vienna',
       'Valencia', 'Basel', 'Kitzbhel', 'Bâ€ stad', 'Kitzbuhel',
       'Monte-Carlo', 'Oeiras', 'Dusseldorf', 'Istanbul', 'Geneva',
       'Nottingham', 'Sofia', 'Marrakech', 'Antwerp', 'Budapest', 'Lyon',
       'Antalya'], dtype=object)

In [16]:
# c.get_city(city_name="Doha",country_code_iso='QA')

In [17]:
# Create a dictionary mapping city names to country codes
country_codes = {
    'Brisbane': 'AU',
    'Doha': 'QA',
    'Chennai': 'IN',
    'Sydney': 'AU',
    'Auckland': 'NZ',
    'Johannesburg': 'ZA',
    'Santiago': 'CL',
    'San Jose': 'CR',
    'Costa do Sauipe': 'BR',
    'Memphis': 'US',
    'Buenos Aires': 'AR',
    'Dubai, United Arab Emirates': 'AE',
    'Acapulco, Mexico': 'MX',
    'Delray Beach': 'US',
    'Indian Wells': 'US',
    'Miami': 'US',
    'Houston, United States': 'US',
    'Newport, United States': 'US',
    'Atlanta, United States': 'US',
    'Los Angeles, United States': 'US',
    'Washington, United States': 'US',
    'Toronto, Canada': 'CA',
    'Cincinnati, United States': 'US',
    'New Haven': 'US',
    'New York': 'US',
    'Kuala Lumpur': 'MY',
    'Bangkok': 'TH',
    'Beijing, China': 'CN',
    'Tokyo': 'JP',
    'Shanghai, China': 'CN',
    'Moscow, Russia': 'RU',
    'St. Petersburg, Russia': 'RU',
    'London, Great Britain': 'GB',
    'Brisbane, Australia': 'AU',
    'Doha, Qatar': 'QA',
    'Chennai, India': 'IN',
    'Sydney, Australia': 'AU',
    'Auckland, New Zealand': 'NZ',
    'Johannesburg, South Africa': 'ZA',
    'Santiago, Chile': 'CL',
    'San Jose, United States': 'CR',
    'Costa do Sauipe, Brazil': 'BR',
    'Memphis, United States': 'US',
    'Buenos Aires, Argentina': 'AR',
    'Delray Beach, United States': 'US',
    'Indian Wells, United States': 'US',
    'Miami, United States': 'US',
    'Montreal, Canada': 'CA',
    'Winston-Salem, United States': 'US',
    'New York, United States': 'US',
    'Kuala Lumpur, Malaysia': 'MY',
    'Bangkok, Thailand': 'TH',
    'Tokyo, Japan': 'JP',
    'Vina del Mar, Chile': 'CL',
    'Sao Paulo, Brazil': 'BR',
    'Bogota, Colombia': 'CO',
    'Rio de Janeiro, Brazil': 'BR',
    'New York City, United States': 'US',
    'Shenzhen, China': 'CN',
    'Quito, Ecuador': 'EC',
    'Los Cabos, Mexico': 'MX',
    'Chengdu, China': 'CN',
    'Milan, Italy': 'IT',
    'Pune, India': 'IN',
    'Cordoba, Argentina': 'AR',
    'Zhuhai, China': 'CN',
    'Melbourne': 'AU',
    'Melbourne, Australia': 'AU',
    'Zagreb': 'HR',
    'Rotterdam': 'NL',
    'Marseille, France': 'FR',
    'Casablanca': 'MA',
    'Monte Carlo': 'MC',
    'Barcelona': 'ES',
    'Rome': 'IT',
    'Munich': 'DE',
    'Estoril': 'PT',
    'Belgrade': 'RS',
    'Madrid': 'ES',
    'Nice': 'FR',
    'Paris': 'FR',
    'Halle': 'DE',
    'Eastbourne': 'GB',
    's-Hertogenbosch': 'NL',
    'Bastad': 'SE',
    'Stuttgart': 'DE',
    'Hamburg': 'DE',
    'Gstaad': 'CH',
    'Umag': 'HR',
    'Metz': 'FR',
    'Bucharest': 'RO',
    'Stockholm': 'SE',
    'Montpellier': 'FR',
    'Vienna': 'AT',
    'Valencia': 'ES',
    'Basel': 'CH',
    'Zagreb': 'HR',
    'Rotterdam': 'NL',
    'Casablanca': 'MA',
    'Monte Carlo': 'MC',
    'Barcelona': 'ES',
    'Estoril': 'PT',
    'Belgrade': 'RS',
    'Rome': 'IT',
    'Kitzbuhel': 'AT',
    'Metz': 'FR',
    'Bucharest': 'RO',
    'Stockholm': 'SE',
    'Valencia': 'ES',
    'Bastad': 'SE',
    'Kitzbuhel': 'AT',
    'Monte-Carlo': 'MC',
    'Oeiras': 'PT',
    'Dusseldorf': 'DE',
    'Istanbul': 'TR',
    'Geneva': 'CH',
    'Nottingham': 'GB',
    'Sofia': 'BG',
    'Marrakech': 'MA',
    'Antwerp': 'BE',
    'Budapest': 'HU',
    'Lyon': 'FR',
    'Antalya': 'TR',
    'Munich, Germany' : 'DEU',
    'Madrid, Spain' : 'ESP',
    'Nice, France' : 'FRA',
    'Paris, France' : 'FRA',
    'Halle, Germany' : 'DEU',
    'Eastbourne, Great Britain' : 'GBR',
    's-Hertogenbosch, Netherlands' : 'NLD',
    'Bastad, Sweden' : 'SWE',
    'Stuttgart, Germany' : 'DEU',
    'Hamburg, Germany' : 'DEU',
    'Gstaad, Switzerland' : 'CHE',
    'Umag, Croatia' : 'HRV',
    'Montpellier, France' : 'FRA',
    'Vienna, Austria' : 'AUT',
    'Valencia, Switzerland' : 'CHE',
    'Basel, Switzerland' : 'CHE',
    'Zagreb, Croatia' : 'HRV',
    'Rotterdam, Netherlands' : 'NLD',
    'Casablanca, Morocco' : 'MAR',
    'Monte Carlo, Monaco' : 'MCO',
    'Barcelona, Spain' : 'ESP',
    'Estoril, Portugal' : 'PRT',
    'Belgrade, Serbia' : 'SRB',
    'Rome, Italy' : 'ITA',
    'Kitzbhel, Austria' : 'AUT',
    'Metz, France' : 'FRA',
    'Bucharest, Romania' : 'ROU',
    'Stockholm, Sweden' : 'SWE',
    'Valencia, Spain' : 'ESP',
    'Bâ€ stad, Sweden' : 'SWE',
    'Kitzbuhel, Austria' : 'AUT',
    'Monte-Carlo, Monaco' : 'MCO',
    'Oeiras, Portugal' : 'PRT',
    'Dusseldorf, Germany' : 'DEU',
    'Istanbul, Turkey': 'TR',
    'Geneva, Switzerland': 'CH',
    'Nottingham, Great Britain': 'GB',
    'Sofia, Bulgaria': 'BG',
    'Marrakech, Morocco': 'MA',
    'Antwerp, Belgium': 'BE',
    'Budapest, Hungary': 'HU',
    'Lyon, France': 'FR',
    'Antalya, Turkey': 'TR'
}

In [18]:
# Create a new column called "CountryCode"
tournaments['CountryCode'] = ''

# Loop over the rows of the data frame and map the country names to country codes
for i, row in tournaments.iterrows():
    country_name = row['tourney_location']
    if country_name in country_codes:
        country_code = country_codes[country_name]
    else:
        country_code = 'Unknown'  # Set the country code as 'Unknown' if not found in the dictionary
    tournaments.loc[i, 'CountryCode'] = country_code

In [19]:
# create empty columns for latitude and longitude
tournaments['latitude'] = ""
tournaments['longitude'] = ""

# iterate through the rows of the dataframe
for i, row in tournaments.iterrows():
    # get the city name from the 'city' column and convert to lowercase
    city = row['tourney_city']
    code = row['CountryCode']
    try:
        # use the CityCoordinator object to get the coordinates for the city
        result = c.get_city(city_name=city, country_code_iso=code)

        # extract the latitude and longitude from the result and add to the dataframe
        tournaments.at[i, 'latitude'] = result['location']['lat']
        tournaments.at[i, 'longitude'] = result['location']['lon']
    except:
        # if the city name is not found, set the latitude and longitude to NaN
        tournaments.at[i, 'latitude'] = float('nan')
        tournaments.at[i, 'longitude'] = float('nan')

In [20]:
tournaments

,Unnamed: 0,tourney_year_id,tourney_order,tourney_type,tourney_name,tourney_id,tourney_slug,tourney_location,tourney_date,year,...,doubles_winner_2_name,doubles_winner_2_player_slug,doubles_winner_2_player_id,tourney_fin_commit_USD,tourney_region,tourney_city,country_code,latitude,longitude,CountryCode
0,0,2010-339,1,ATP 250,Brisbane,339,brisbane,Brisbane,2010-01-03,2010,...,Marc Gicquel,marc-gicquel,g436,424250.0,Oceania,Brisbane,AU,NaN,NaN,AU
1,1,2010-451,2,ATP 250,Doha,451,doha,Doha,2010-01-04,2010,...,Albert Montanes,albert-montanes,m824,1110250.0,Asia,Doha,QA,NaN,NaN,QA
2,2,2010-891,3,ATP 250,Chennai,891,chennai,Chennai,2010-01-04,2010,...,Santiago Ventura,santiago-ventura,v251,450000.0,Asia,Chennai,IN,NaN,NaN,IN
3,3,2010-338,4,ATP 250,Sydney,338,sydney,Sydney,2010-01-11,2010,...,Nenad Zimonjic,nenad-zimonjic,z072,424250.0,Oceania,Sydney,AU,NaN,NaN,AU
4,4,2010-301,5,ATP 250,Auckland,301,auckland,Auckland,2010-01-11,2010,...,Horia Tecau,horia-tecau,t749,407250.0,Oceania,Auckland,NZ,NaN,NaN,NZ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,655,2015-540,39,Grand Slam,Wimbledon,540,wimbledon,"London, Great Britain",2015-06-29,2015,...,Horia Tecau,horia-tecau,t749,15124331.2,Europe,London,GB,NaN,NaN,GB
656,656,2016-540,39,Grand Slam,Wimbledon,540,wimbledon,"London, Great Britain",2016-06-27,2016,...,Nicolas Mahut,nicolas-mahut,m873,15840354.2,Europe,London,GB,NaN,NaN,GB
657,657,2017-540,40,Grand Slam,Wimbledon,540,wimbledon,"London, Great Britain",2017-07-03,2017,...,Marcelo Melo,marcelo-melo,m919,17858456.0,Europe,London,GB,NaN,NaN,GB
658,658,2018-540,40,Grand Slam,Wimbledon,540,wimbledon,"London, Great Britain",2018-07-02,2018,...,Jack Sock,jack-sock,sm25,19232738.8,Europe,London,GB,NaN,NaN,GB
659,659,2019-540,39,Grand Slam,Wimbledon,540,wimbledon,"London, Great Britain",2019-07-01,2019,...,Robert Farah,robert-farah,f525,21383214.6,Europe,London,GB,NaN,NaN,GB

In [21]:
# Load a GeoJson file from path
import json 

with open('countries.geojson') as f:
    data_geo = json.load(f)

In [22]:
#para q serve isto?? funciona sem isto

for feature in data_geo['features']:
    feature['id'] = feature['properties']['ADMIN']   # or 'ISO-A3'

In [23]:
data_scattermap = dict(type='scattermapbox', 
                       lat=tournaments['latitude'], 
                       lon=tournaments['longitude'],
                       
                       mode=['markers', 'lines', 'text'][0],
                       text=tournaments['tourney_name'], #marker wll show the name of the tournament
                       marker=dict(color='magenta',
                                   opacity = 0.4,
                                   size=10
                                  )
                      )


layout_scattermap = dict(mapbox=dict(style='white-bg',
                                     layers=[dict(source=feature,
                                                  below='traces',
                                                  type='fill',
                                                  fill=dict(outlinecolor='gray')
                                                         ) for feature in data_geo['features']]
                                      ),
                         title=dict(text='World Map',
                                    x=.5 # Title relative position according to the xaxis, range (0,1)
                                   )
                           )

fig_scattermap = go.Figure(data=data_scattermap, layout=layout_scattermap)

# fig_scattermap.show()

In [24]:
# tournaments = pd.read_csv('tournaments_preparation.csv')

In [25]:
# def update_map(year):

#     tournaments_filtered = tournaments[tournaments['year'] == year]

#     data_scattermap = dict(type='scattermapbox', 
#                            lat=tournaments_filtered['latitude'], 
#                            lon=tournaments_filtered['longitude'],
                        
#                            mode=['markers', 'lines', 'text'][0],
#                            text=tournaments_filtered['tourney_name'], #marker wll show the name of the tournament
#                            marker=dict(color='rgb(223, 255, 138)',
#                                        opacity = 0.8,
#                                        size=10
#                                       )
#                            )


#     layout_scattermap = dict(mapbox=dict(style='white-bg',
#                                          layers=[dict(source=feature,
#                                                       below='traces',
#                                                       type='fill',
#                                                       fill=dict(outlinecolor='gray')
#                                                      ) for feature in data_geo['features']]
#                                         ),
#                             title=dict(text='World Map',
#                                         x=.5 # Title relative position according to the xaxis, range (0,1)
#                                     )
#                             )

#     fig_scattermap = go.Figure(data=data_scattermap, layout=layout_scattermap)

#     return fig_scattermap

# update_map(2012)

# Country points version

In [26]:
# Create a dictionary mapping city names to country codes
country_codes = {
    'Brisbane': 'AU',
    'Doha': 'QA',
    'Chennai': 'IN',
    'Sydney': 'AU',
    'Auckland': 'NZ',
    'Johannesburg': 'ZA',
    'Santiago': 'CL',
    'San Jose': 'CR',
    'Costa do Sauipe': 'BR',
    'Memphis': 'US',
    'Buenos Aires': 'AR',
    'Dubai, United Arab Emirates': 'AE',
    'Acapulco, Mexico': 'MX',
    'Delray Beach': 'US',
    'Indian Wells': 'US',
    'Miami': 'US',
    'Houston, United States': 'US',
    'Newport, United States': 'US',
    'Atlanta, United States': 'US',
    'Los Angeles, United States': 'US',
    'Washington, United States': 'US',
    'Toronto, Canada': 'CA',
    'Cincinnati, United States': 'US',
    'New Haven': 'US',
    'New York': 'US',
    'Kuala Lumpur': 'MY',
    'Bangkok': 'TH',
    'Beijing, China': 'CN',
    'Tokyo': 'JP',
    'Shanghai, China': 'CN',
    'Moscow, Russia': 'RU',
    'St. Petersburg, Russia': 'RU',
    'London, Great Britain': 'GB',
    'Brisbane, Australia': 'AU',
    'Doha, Qatar': 'QA',
    'Chennai, India': 'IN',
    'Sydney, Australia': 'AU',
    'Auckland, New Zealand': 'NZ',
    'Johannesburg, South Africa': 'ZA',
    'Santiago, Chile': 'CL',
    'San Jose, United States': 'CR',
    'Costa do Sauipe, Brazil': 'BR',
    'Memphis, United States': 'US',
    'Buenos Aires, Argentina': 'AR',
    'Delray Beach, United States': 'US',
    'Indian Wells, United States': 'US',
    'Miami, United States': 'US',
    'Montreal, Canada': 'CA',
    'Winston-Salem, United States': 'US',
    'New York, United States': 'US',
    'Kuala Lumpur, Malaysia': 'MY',
    'Bangkok, Thailand': 'TH',
    'Tokyo, Japan': 'JP',
    'Vina del Mar, Chile': 'CL',
    'Sao Paulo, Brazil': 'BR',
    'Bogota, Colombia': 'CO',
    'Rio de Janeiro, Brazil': 'BR',
    'New York City, United States': 'US',
    'Shenzhen, China': 'CN',
    'Quito, Ecuador': 'EC',
    'Los Cabos, Mexico': 'MX',
    'Chengdu, China': 'CN',
    'Milan, Italy': 'IT',
    'Pune, India': 'IN',
    'Cordoba, Argentina': 'AR',
    'Zhuhai, China': 'CN',
    'Melbourne': 'AU',
    'Melbourne, Australia': 'AU',
    'Zagreb': 'HR',
    'Rotterdam': 'NL',
    'Marseille, France': 'FR',
    'Casablanca': 'MA',
    'Monte Carlo': 'MC',
    'Barcelona': 'ES',
    'Rome': 'IT',
    'Munich': 'DE',
    'Estoril': 'PT',
    'Belgrade': 'RS',
    'Madrid': 'ES',
    'Nice': 'FR',
    'Paris': 'FR',
    'Halle': 'DE',
    'Eastbourne': 'GB',
    's-Hertogenbosch': 'NL',
    'Bastad': 'SE',
    'Stuttgart': 'DE',
    'Hamburg': 'DE',
    'Gstaad': 'CH',
    'Umag': 'HR',
    'Metz': 'FR',
    'Bucharest': 'RO',
    'Stockholm': 'SE',
    'Montpellier': 'FR',
    'Vienna': 'AT',
    'Valencia': 'ES',
    'Basel': 'CH',
    'Zagreb': 'HR',
    'Rotterdam': 'NL',
    'Casablanca': 'MA',
    'Monte Carlo': 'MC',
    'Barcelona': 'ES',
    'Estoril': 'PT',
    'Belgrade': 'RS',
    'Rome': 'IT',
    'Kitzbuhel': 'AT',
    'Metz': 'FR',
    'Bucharest': 'RO',
    'Stockholm': 'SE',
    'Valencia': 'ES',
    'Bastad': 'SE',
    'Kitzbuhel': 'AT',
    'Monte-Carlo': 'MC',
    'Oeiras': 'PT',
    'Dusseldorf': 'DE',
    'Istanbul': 'TR',
    'Geneva': 'CH',
    'Nottingham': 'GB',
    'Sofia': 'BG',
    'Marrakech': 'MA',
    'Antwerp': 'BE',
    'Budapest': 'HU',
    'Lyon': 'FR',
    'Antalya': 'TR',
    'Munich, Germany' : 'DEU',
    'Madrid, Spain' : 'ESP',
    'Nice, France' : 'FRA',
    'Paris, France' : 'FRA',
    'Halle, Germany' : 'DEU',
    'Eastbourne, Great Britain' : 'GBR',
    's-Hertogenbosch, Netherlands' : 'NLD',
    'Bastad, Sweden' : 'SWE',
    'Stuttgart, Germany' : 'DEU',
    'Hamburg, Germany' : 'DEU',
    'Gstaad, Switzerland' : 'CHE',
    'Umag, Croatia' : 'HRV',
    'Montpellier, France' : 'FRA',
    'Vienna, Austria' : 'AUT',
    'Valencia, Switzerland' : 'CHE',
    'Basel, Switzerland' : 'CHE',
    'Zagreb, Croatia' : 'HRV',
    'Rotterdam, Netherlands' : 'NLD',
    'Casablanca, Morocco' : 'MAR',
    'Monte Carlo, Monaco' : 'MCO',
    'Barcelona, Spain' : 'ESP',
    'Estoril, Portugal' : 'PRT',
    'Belgrade, Serbia' : 'SRB',
    'Rome, Italy' : 'ITA',
    'Kitzbhel, Austria' : 'AUT',
    'Metz, France' : 'FRA',
    'Bucharest, Romania' : 'ROU',
    'Stockholm, Sweden' : 'SWE',
    'Valencia, Spain' : 'ESP',
    'Bâ€ stad, Sweden' : 'SWE',
    'Kitzbuhel, Austria' : 'AUT',
    'Monte-Carlo, Monaco' : 'MCO',
    'Oeiras, Portugal' : 'PRT',
    'Dusseldorf, Germany' : 'DEU',
    'Istanbul, Turkey': 'TR',
    'Geneva, Switzerland': 'CH',
    'Nottingham, Great Britain': 'GB',
    'Sofia, Bulgaria': 'BG',
    'Marrakech, Morocco': 'MA',
    'Antwerp, Belgium': 'BE',
    'Budapest, Hungary': 'HU',
    'Lyon, France': 'FR',
    'Antalya, Turkey': 'TR'
}

In [27]:
# Create a new column called "CountryCode"
tournaments['CountryCode'] = ''

# Loop over the rows of the data frame and map the country names to country codes
for i, row in tournaments.iterrows():
    country_name = row['tourney_location']
    if country_name in country_codes:
        country_code = country_codes[country_name]
    else:
        country_code = 'Unknown'  # Set the country code as 'Unknown' if not found in the dictionary
    tournaments.loc[i, 'CountryCode'] = country_code

In [28]:
tournaments.head()

,Unnamed: 0,tourney_year_id,tourney_order,tourney_type,tourney_name,tourney_id,tourney_slug,tourney_location,tourney_date,year,...,doubles_winner_2_name,doubles_winner_2_player_slug,doubles_winner_2_player_id,tourney_fin_commit_USD,tourney_region,tourney_city,country_code,latitude,longitude,CountryCode
0,0,2010-339,1,ATP 250,Brisbane,339,brisbane,Brisbane,2010-01-03,2010,...,Marc Gicquel,marc-gicquel,g436,424250.0,Oceania,Brisbane,AU,NaN,NaN,AU
1,1,2010-451,2,ATP 250,Doha,451,doha,Doha,2010-01-04,2010,...,Albert Montanes,albert-montanes,m824,1110250.0,Asia,Doha,QA,NaN,NaN,QA
2,2,2010-891,3,ATP 250,Chennai,891,chennai,Chennai,2010-01-04,2010,...,Santiago Ventura,santiago-ventura,v251,450000.0,Asia,Chennai,IN,NaN,NaN,IN
3,3,2010-338,4,ATP 250,Sydney,338,sydney,Sydney,2010-01-11,2010,...,Nenad Zimonjic,nenad-zimonjic,z072,424250.0,Oceania,Sydney,AU,NaN,NaN,AU
4,4,2010-301,5,ATP 250,Auckland,301,auckland,Auckland,2010-01-11,2010,...,Horia Tecau,horia-tecau,t749,407250.0,Oceania,Auckland,NZ,NaN,NaN,NZ

In [29]:
tournaments['CountryCode'].unique()

array(['AU', 'QA', 'IN', 'NZ', 'ZA', 'CL', 'CR', 'BR', 'US', 'AR', 'AE',
       'MX', 'CA', 'MY', 'TH', 'CN', 'JP', 'RU', 'GB', 'CO', 'EC', 'IT',
       'HR', 'NL', 'FR', 'MA', 'MC', 'ES', 'DEU', 'PT', 'RS', 'ESP',
       'FRA', 'GBR', 'NLD', 'SWE', 'CHE', 'HRV', 'RO', 'SE', 'AUT', 'MAR',
       'MCO', 'PRT', 'SRB', 'ITA', 'ROU', 'TR', 'CH', 'BG', 'BE', 'HU'],
      dtype=object)

In [30]:
# tournaments_map = pd.merge(tournaments, country_points, left_on='CountryCode', right_on='country', how='left')

In [31]:
# tournaments_map.head()

In [32]:
# tournaments_map['tourney_year'] = tournaments_map['tourney_date'].str.split('-').str[0]

In [33]:
# tournaments_map['tourney_year'].unique()

In [34]:
# data_scattergeo = dict(type='scattergeo', 
#                        lat=tournaments_map['latitude'], #the only difference from a normal scatterplot is the lat and lon
#                        lon=tournaments_map['longitude'],
                       
#                        mode=['markers', 'lines', 'text'][0],
#                        text=tournaments_map['name'],
#                        marker=dict(color='red',
#                                    opacity = 0.3,
#                                    size=12
#                                   )
#                       )

# layout_scattergeo = dict(geo=dict(scope='world',  #default
#                                   projection=dict(type='equirectangular' #or equirectangular or orthographic and others
#                                                  ),
#                                   #showland=True,   #default
#                                   landcolor='black',
#                                   lakecolor='white'
#                                  ),
                         
#                          title=dict(text='World Map',
#                                     x=.5 # Title relative position according to the xaxis, range (0,1)
#                                    )
#                          ,
#                          sliders=[dict(
#                             active=0, # starting year
#                             currentvalue={"prefix": "Year: "},
#                             pad={"t": 50},
#                             steps=[{
#                                 "label": str(year),
#                                 "method": "update",
#                                 "args": [
#                                     {"visible": tournaments_map['tourney_year'] == year},
#                                     {"title": f"World Map - {year}"}
#                                 ]
#                             } for year in sorted(tournaments_map['tourney_year'].unique())]
#                         )]
#                         )

In [35]:
# fig_scattergeo = go.Figure(data=data_scattergeo, layout=layout_scattergeo)

# fig_scattergeo.show()

In [36]:
# slider_steps = []

# for year in sorted(tournaments_map['tourney_year'].unique()):
#     visible_points = tournaments_map['tourney_year'] == year
#     scatter_geo = dict(type='scattergeo', 
#                        lat=tournaments_map[visible_points]['latitude'],
#                        lon=tournaments_map[visible_points]['longitude'],
#                        mode='markers',
#                        text=tournaments_map[visible_points]['name'],
#                        marker=dict(color='red', size=3)
#                       )
    
#     slider_step = dict(
#         label=str(year),
#         method='update',
#         args=[
#             {'data': [scatter_geo]},
#             {'title': f"World Map - {year}"}
#         ]
#     )
    
#     slider_steps.append(slider_step)
    
# data_scattergeo = dict(type='scattergeo', 
#                        lat=tournaments_map['latitude'], #the only difference from a normal scatterplot is the lat and lon
#                        lon=tournaments_map['longitude'],
                       
#                        mode=['markers', 'lines', 'text'][0],
#                        text=tournaments_map['name'],
#                        marker=dict(color='red',
#                                    opacity = 0.3,
#                                    size=12
#                                   )
#                       )

# layout_scattergeo = dict(geo=dict(scope='world',  #default
#                                   projection=dict(type='equirectangular' #or equirectangular or orthographic and others
#                                                  ),
#                                   #showland=True,   #default
#                                   landcolor='papayawhip',
#                                   lakecolor='white'
#                                  ),
                         
#                          title=dict(text='World Map',
#                                     x=.5 # Title relative position according to the xaxis, range (0,1)
#                                    )
#                          ,
#                          sliders=[dict(
#                                     active=0,
#                                     steps=slider_steps,
#                                     currentvalue={"prefix": "Year: "},
#                                     pad={"t": 50}
#                                 )]
#                         )

In [37]:
# fig_scattergeo = go.Figure(data=data_scattergeo, layout=layout_scattergeo)

# fig_scattergeo.show()

In [38]:
# # An empty graph object
# fig_map = go.Figure()

# # Each year defines a new hidden (implies visible=False) trace in our visualization
# for year in tournaments_map['tourney_year'].unique():
#     fig_map.add_trace(dict(type='scattergeo', 
#                        lat=tournaments_map['latitude'], 
#                        lon=tournaments_map['longitude'],
                       
#                        mode=['markers', 'lines', 'text'][0],
#                        text=tournaments_map['name'],
#                        marker=dict(color='red',
#                                    opacity = 0.3,
#                                    size=12
#                                   )
#                     )
#                )

# # First seen trace
# fig_map.data[0].visible = True


# # Lets create our slider, one option for each trace
# steps = []
# for i in range(len(fig_map.data)):
#     step = dict(
#         label='Year ' + str(2010 + i),
#         method="restyle", #there are four methods restyle changes the type of an argument (in this case if visible or not)
#         args=["visible", [False] * len(fig_map.data)], # Changes all to Not visible
#     )
#     step["args"][1][i] = True  # Toggle i'th trace to "visible"
#     steps.append(step)

    
# sliders = [dict(
#     active=2010,
#     pad={"t": 100},
#     steps=steps
# )]


# fig_map.update_layout(dict(geo=dict(scope='world',  #default
#                                   projection=dict(type='equirectangular' #or equirectangular or orthographic and others
#                                                  ),
#                                   #showland=True,   #default
#                                   landcolor='papayawhip',
#                                   lakecolor='white'
#                                  ),
                         
#                          title=dict(text='World Map',
#                                     x=.5 # Title relative position according to the xaxis, range (0,1)
#                                    )
#                          ,
#                   sliders=sliders))

# # fig_map.show(renderer='iframe')

In [39]:
# # Load a GeoJson file from path
# import json 

# with open('/Users/macbookair/Desktop/dv/dv group work/data-visualization-project-main/countries.geojson') as f:
#     data_geo = json.load(f)

In [40]:
# #para q serve isto?? funciona sem isto

# for feature in data_geo['features']:
#     feature['id'] = feature['properties']['ADMIN']   # or 'ISO-A3'

In [41]:
# data_scattermap = dict(type='scattermapbox', 
#                        lat=tournaments_map['latitude'], 
#                        lon=tournaments_map['longitude'],
                       
#                        mode=['markers', 'lines', 'text'][0],
#                        text=tournaments_map['name'],
#                        marker=dict(color='magenta',
#                                    opacity = 0.8,
#                                    size=6
#                                   )
#                       )


# layout_scattermap = dict(mapbox=dict(style='white-bg',
#                                      layers=[dict(source=feature,
#                                                   below='traces',
#                                                   type='fill',
#                                                   fill=dict(outlinecolor='gray')
#                                                          ) for feature in data_geo['features']]
#                                       ),
#                          title=dict(text='World Map',
#                                     x=.5 # Title relative position according to the xaxis, range (0,1)
#                                    )
#                            )

#fig_scattermap = go.Figure(data=data_scattermap, layout=layout_scattermap)

#fig_scattermap.show()

In [42]:
#fig_scattermap = go.Figure(data=data_scattermap, layout=layout_scattermap)

#fig_scattermap.show()

In [43]:
# # count the number of observations per country
# country_counts = tournaments_map['CountryCode'].value_counts()

# # define the marker size based on the number of observations per country
# marker_sizes = [12 if country_counts.get(country, 0) > 50 else 8 for country in tournaments_map['country']]


# data_scattermap = dict(type='scattermapbox', 
#                        lat=tournaments_map['latitude'], 
#                        lon=tournaments_map['longitude'],
                       
#                        mode=['markers', 'lines', 'text'][0],
#                        text=tournaments_map['name'],
#                        marker=dict(color='magenta',
#                                    opacity = 0.7, 
#                                    size=marker_sizes
#                                   )
#                       )

# layout_scattermap = dict(mapbox=dict(style='white-bg',
#                                      layers=[dict(source=feature,
#                                                   below='traces',
#                                                   type='fill',
#                                                   fill=dict(outlinecolor='gray')
#                                                          ) for feature in data_geo['features']]
#                                       ),
#                          title=dict(text='World Map',
#                                     x=.5 # Title relative position according to the xaxis, range (0,1)
#                                    )
#                            )

In [44]:
# tournaments_map['CountryCode'].value_counts()

In [45]:
# fig_scattermap = go.Figure(data=data_scattermap, layout=layout_scattermap)

# fig_scattermap.show()

In [46]:
# import numpy as np
# import pandas as pd
# import plotly.graph_objs as go
# import plotly.plotly as py

# # min year in your dataset
# year = 2010

# # your color-scale
# scl = [[0.0, '#ffffff'],[0.2, '#b4a8ce'],[0.4, '#8573a9'],
#        [0.6, '#7159a3'],[0.8, '#5732a1'],[1.0, '#2c0579']] # purples

# data_slider = []
# for year in tournaments_map['tourney_year'].unique():
#     df_segmented =  tournaments_map[(tournaments_map['tourney_year']== year)]

#     for col in df_segmented.columns:
#         df_segmented[col] = df_segmented[col].astype(str)

#     data_each_yr = dict(
#                         type='choropleth',
#                         locations = df_segmented['state'],
#                         z=df_segmented['sightings'].astype(float),
#                         locationmode='USA-states',
#                         colorscale = scl,
#                         colorbar= {'title':'# Sightings'})

#     data_slider.append(data_each_yr)

# steps = []
# for i in range(len(data_slider)):
#     step = dict(method='restyle',
#                 args=['visible', [False] * len(data_slider)],
#                 label='Year {}'.format(i + 1998))
#     step['args'][1][i] = True
#     steps.append(step)

# sliders = [dict(active=0, pad={"t": 1}, steps=steps)]

# layout = dict(title ='UFO Sightings by State Since 1998', geo=dict(scope='usa',
#                        projection={'type': 'albers usa'}),
#               sliders=sliders)

# fig = dict(data=data_slider, layout=layout)
# periscope.plotly(fig)